name: Build
on:
  release:
    types: [published]

jobs:
  staging:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: monom-cicd-tools
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: gcloud auth configure-docker

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gcr.io/monom-cicd-tools/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}

      - name: Slack notification
        uses: act10ns/slack@v1
        if: always()
        with:
          status: ${{ job.status }}
          channel: '#deployments'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
